on:
  push:
    branches:
    - main

- name: Doxygen Action
  # You may pin to the exact commit or the version.
  # uses: mattnotmitt/doxygen-action@411df0c62acb5b96b8a93d93a7bf4b753c47ea05
  uses: mattnotmitt/doxygen-action@1.9.5
  with:
    doxyfile-path: ./Doxyfile
    working-directory: .
